apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vault-images
  name: vault-images
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vault-images
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vault-images
    spec:
      containers:
      - image: bossmanjerry/vault-images:101
        name: vault-images
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: vault-images
