# playbook.yml
- name: Apply Argo CD Application
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Ensure kubectl is installed
      command: kubectl version --client
      register: kubectl_installed
      ignore_errors: true

    - name: Install kubectl if not present
      package:
        name: kubectl
        state: present
      when: kubectl_installed.failed

    - name: Apply Argo CD Application YAML
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'application.yaml') }}"
