---
- name: Deploy Application using ArgoCD
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: Create Application
      command: >
        argocd app create my-app
        --repo=https://github.com/your/repo
        --path=my-app
        --dest-server=https://kubernetes.default.svc
        --dest-namespace=default
        --revision=HEAD
        --auto-sync
